### ISSUE TITLE
Change favicon to Bulgaria

### ISSUE THREAD

**Issue by antaldaniel** [dataobservatory-eu/bulgaria.listen-local.net#1]
assets/media/icon.png and sav to Bulgarian

**Comment by antaldaniel** [comment]
The icon and the favicon are generated now from PowerPoint.  I will create a master template and and instructions how to change it for any site. I think that this is done

**Comment by antaldaniel** [comment]
@liaugminaite my screen is simply to small to see if the favicon is now in Bulgarian colors or not.  What do you think?

**Comment by liaugminaite** [comment]
I'm pretty sure it's the Bulgarian flag
